name: Build and Package Docker PDF Server

on:
  push:
    branches:
      - main
      - beta

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm install -g semantic-release @semantic-release/commit-analyzer @semantic-release/changelog @semantic-release/git @semantic-release/release-notes-generator
          npx semantic-release

      - name: Login to Docker Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and push Docker Image
        run: |
          VERSION=$(node -p "require('./package.json').version")
          docker build --platform linux/amd64 -t ghcr.io/ash0ne/docker-pdf-server:${VERSION} .
          docker push ghcr.io/ash0ne/docker-pdf-server:${VERSION}
          docker tag ghcr.io/ash0ne/docker-pdf-server:${VERSION} ghcr.io/ash0ne/docker-pdf-server:latest
          docker push ghcr.io/ash0ne/docker-pdf-server:latest

      - name: Logout from Docker Registry
        run: docker logout ghcr.io
